--CLASS 2--
--CREATE DATABASE--
CREATE DATABASE  SUFAUNIVERSITY

--CREATE TABLE--
CREATE TABLE CANDIDATES (
ID INT,
NAME VARCHAR(100),
AGE INT,
ADMISSION_DATE DATE ,

);
SELECT *FROM CANDIDATES;

 